server {
    listen 3000; # Tu imagen usa el 3000, déjalo así.
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy inverso corregido
    location /api/ {
        # CAMBIO: Agregamos -dev al nombre del host
        set $backend "api-gateway-dev:8080"; 
        proxy_pass http://$backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}